### ISSUE TITLE
Must there be a normal image of the same scene to enhance a severe weather image?

### ISSUE THREAD

**Issue by 010327Zy** [Jumponthemoon/AllWeatherNet#3]
I noticed that the data section requires the folder of normal data

**Comment by Jumponthemoon** [comment]
No. The inference only requires weather image input; you don't have to prepare the paired normal weather image.

The normal weather folder you see in the dataset section is required for training.

**Comment by 010327Zy** [comment]
> 不。推理只需要天气图像输入;您不必准备配对的 Normal Weather 图像。
> 
> 您在数据集部分看到的 normal weather 文件夹是训练所必需的。

Thank you for your reply, what is the torch version of the pre-trained model My downloaded torch version is torch 0.3.1 but it appears when loading the pre-trained model in the readme
_pickle. UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
Error

**Comment by Jumponthemoon** [comment]
Our test machine uses torch 1.8.0, and cuda 11.1 and the 'requirements.txt' is actually inherited from the legacy code. Sorry for the inconvenience.

I have updated the test code and added a new instruction to simplify the demo usage. Please feel free to re-download the code and check it out.

**Comment by 010327Zy** [comment]
> 我们的测试机器使用 torch 1.8.0 和 cuda 11.1，而 'requirements.txt' 实际上是从遗留代码继承的。很抱歉给您带来不便。
> 
> 我更新了测试代码并添加了一条新指令来简化演示的使用。请随时重新下载代码并检查。

Thank you for your timely reply. The code can now be reasoned normally, but I have a question. What are the functions of the testB folder and testA during the test? What should I do if I only need to enhance the images in a single folder?

**Comment by Jumponthemoon** [comment]
They are just a template for loading test images as required by dataset loader interface in the code.

As explained in the README.md, you can create your own test dataset by organizing the files in the following structure:
1. Add a root folder named 'test' that contains two subfolders named testA and testB.
2. Place all your images to be enhanced in the testA folder.
3. Add a placeholder image in the testB folder.
4. Change the 'dataroot' path on the line 43 of 'scripts/script.py'

So if you want to enhance the images in a single folder, you can put that folder under 'test_data' and rename it with 'testA'.

**Comment by D7racarys** [comment]
Hello, I ran the command:
`python train.py --dataroot /AllWeather-Net/datasets/fog_test`

for testing, the organization of the dataset is as follows:



    |-->fog_test

         |-->trainA
               |-->GOPR0475_frame_000041_rgb_anon.png
               ……
         |-->trainB
               |-->GOPR0475_frame_000041_rgb_ref_anon.png
               ……
But an error occurred.

> Original Traceback (most recent call last):
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/luochao/Paper/AllWeather-Net/models/networks.py", line 498, in forward
    return self.model(input)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/luochao/.conda/envs/allweathernet3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not tuple

I would like to know whether this issue is caused by the organization of the dataset or a problem in the code.Thank you very much.
